### ISSUE TITLE
Bash highlighting glitches with weird combination of curly braces

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#7] opened 2014-12-22 12:28 UTC
_From @asciifaceman on October 13, 2014 18:12_

I had this line in a function:

```
sentEmails=`mysql ${OPT_DEFT:+--defaults-file="${OPT_DEFT}"} -Dinventory -ss -e "${query}"`
```

Everything after it was highlighted yellow (as in inside a brace). I am not 100% sure waht on this line is causing it, but I have narrowed it down to this:

```
${OPT_DEFT:+--defaults-file="${OPT_DEFT}"} 
```

The one query is edited out for sensitivity but the other is less important so I left it as the demonstration for highlighting. 

![screen shot 2014-10-13 at 11 00 58 am](https://cloud.githubusercontent.com/assets/1619591/4617910/697caf14-5304-11e4-8661-089e946a9a06.png)

note: this is fully functional and tested code, I don't know where the highlighter is choking 

_Copied from original issue: SublimeTextBugs/Issues#519_

**Comment by keith-hall** [comment] 2017-03-27 08:50
this can be fixed by adding `- include: variable` to above this line: https://github.com/sublimehq/Packages/blob/9fec9a5ec1fb96b52097fe3d9f8a1fa0834947c3/ShellScript/Shell-Unix-Generic.sublime-syntax#L558

I'm not going to create a PR though, due to https://github.com/sublimehq/Packages/issues/434

**Comment by FichteFoll** [comment] 2017-11-08 16:40
Cannot reproduce on 3153 anymore, most likely fixed with https://github.com/sublimehq/Packages/pull/1057.

**Closed by FichteFoll** 2017-11-08 16:40 UTC
Labels: S: minor, T: bug, with patch
