### ISSUE TITLE
C preprocessor highlighting issue with multi-lines strings

### ISSUE THREAD

**Issue by timlegrand** [SublimeTextIssues/DefaultPackages#126] opened 2015-04-30 09:22 UTC
Hi,

Highlighting seems broken when meeting multi-lines strings declaration splitted with '\'.

Below is a valid C file containing such a string:

    #if defined(VARIABLE)
    # error "This is a long error message that need to   \
        be splitted into two lines to prevent large lines."
    #endif

    bool still_C_code_here = true;
    bool linter_is_lost = true;

Notice the following C code now interpreted as a string content and not as C declarations anymore:

![st-c-highlight-issue](https://cloud.githubusercontent.com/assets/5445110/7409969/febab752-ef2a-11e4-8043-9536361629e5.png)

(NB: the [`C Improved` package](https://packagecontrol.io/packages/C%20Improved) handles it properly)

**Comment by jrappen** [comment] 2016-04-26 17:11
Commit has been merged into sublimehq/packages repo long time ago. Cannot reproduce with Build 3111 on Win x64.

**Closed** 2016-04-26 22:14 UTC
Labels: C: C/C++, R: fixed, S: major, T: bug
