### ISSUE TITLE
Unknown self-closing tags are auto-completed on </ in HTML

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#176] opened 2016-02-18 22:20 UTC
Branched off from #78.

This works as expected for tags like `<img />` but not for seemingly arbitrary tags.
### Reproduction

Have the following text in an HTML file (or syntax):

```
<template>
<price />
<tag></tag>
```

When typing `</` at the end it closes with `</price>`.

Expected behavior: Complete to  `</template>`.

**Comment by keith-hall** [comment] 2016-04-23 18:15
It looks like the `img` tag gets scope `text.html.basic meta.tag.inline.any.html entity.name.tag.inline.any.html` but the `price` tag just gets `text.html.basic meta.tag.other.html entity.name.tag.other.html`. I'm guessing the autocompletion expects self-closing tags to have the `inline` scope. Tested in build 3111.

**Comment by keith-hall** [comment] 2016-04-23 18:25
Surely the expected behavior from the example should be to close the `template` tag?

**Comment by FichteFoll** [comment] 2016-04-23 18:40
Yes.

**Comment by keith-hall** [comment] 2017-05-04 07:02
It seems the way the `close_tag` command works is that it checks if the `/` before the `>` is scoped as `punctuation.definition.tag.end.html` - if it is, then it is skipped when finding the open tag that needs to be closed. So we can update the syntax definition to scope the `/` if it exists before the `>`.

i.e change https://github.com/sublimehq/Packages/blob/54340707ecbf7de99ab5b02b9414258bd27ed403/HTML/HTML.sublime-syntax#L218 and https://github.com/sublimehq/Packages/blob/54340707ecbf7de99ab5b02b9414258bd27ed403/HTML/HTML.sublime-syntax#L208 to look like https://github.com/sublimehq/Packages/blob/54340707ecbf7de99ab5b02b9414258bd27ed403/HTML/HTML.sublime-syntax#L148

**Closed** 2017-05-25 04:23 UTC
Labels: C: HTML, S: trivial, T: bug, with patch
