### ISSUE TITLE
Commenting a line with a SQL query string in PHP not working as expected

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#70] opened 2014-12-22 14:02 UTC
_From @gprasanth on July 8, 2013 7:47_

While editing the following line in a php source file,

    $sql = "SELECT * FROM table;";

when the cursor is inbetween the characters `S` and the first `;` in the line, commenting using `Ctrl + /`, inserts `--` at the beginning of the line - before `$sql`, but it should be inserted just before `SELECT`.

Using Version 2.0.1, Build 2217, Windows 8 x64.

_Copied from original issue: SublimeTextBugs/Issues#90_

**Comment by FichteFoll** [comment] 2016-02-18 00:35
Closing as duplicate of https://github.com/SublimeTextIssues/Core/issues/43.

**Closed by FichteFoll** 2016-02-18 00:35 UTC
Labels: C: PHP, C: SQL, S: minor, T: bug
