### ISSUE TITLE
C++ syntax highlight issue with strings

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#54] opened 2014-12-22 12:52 UTC
_From @carrotstealer on October 10, 2013 15:28_

Version ST3 build 3047, also reproducible with latest ST2

Following sample code isn't highlighted properly:
::somefunction(anotherfunction(), "some text;");
All code below this line recognized as string constant.
To see the problem 3 conditions should be satisfied:
1. :: at the beginning(global scope function)
2. parameter before the string constant is a function call
3. semicolon in string constant

e.g. code samples below parsed properly
somefunction(anotherfunction(), "some text;"); // no :: at the beginning
::somefunction(someparam, "some text;"); // parameter before string constant isn't a function call
::somefunction(anotherfunction(), "some text"); // no semicolon in string constant

_Copied from original issue: SublimeTextBugs/Issues#163_

**Comment by jrappen** [comment] 2016-04-26 17:34
Commit has long been merged into sublimehq/packages repo. Cannot reproduce with Build 3111 on Win x64.

**Closed** 2016-04-26 22:17 UTC
Labels: C: C/C++, R: fixed, S: minor, T: bug
