### ISSUE TITLE
Parenthesis in string confuses Java syntax highlighter 

### ISSUE THREAD

**Issue by wangweij** [SublimeTextIssues/DefaultPackages#148] opened 2015-08-03 01:03 UTC
Pasting the code below into Sublime Text 3 and the 2nd method is considered part of a string literal.

    public class A1 {
	    public static void main(String[] args) throws Exception {
	        throw new Exception
	                ("hello (world)");
	    }

	    void x() {
	    	// Nothing
	    }
	}

However, if I put "throw" and "hello" into one line, it looks OK.

This is Sublime Text b3095 on Ubuntu 14.04.2 64 bit.

![screenshot from 2015-08-03 08 52 05](https://cloud.githubusercontent.com/assets/574013/9029042/6028db1c-39be-11e5-8a50-1e1e8b0a828d.png)

**Comment by chuim** [comment] 2016-01-18 16:54
Just to add an example that seems to trigger the same condition:

    class MyClass {
        String K_STRING = ImaginaryStaticMethod(");");
    
        functionLooksLikeTextAsAllFollowing() {
        }
    }

**Comment by FichteFoll** [comment] 2016-01-18 20:44
@chuim your particular example is a duplicate of the "just-fixed" #172.

**Comment by chuim** [comment] 2016-01-18 22:04
@FichteFoll thanks for the heads up!

**Comment by wbond** [comment] 2016-04-27 17:04
This is fixed in the latest syntax from https://github.com/sublimehq/Packages, and will be part of dev build 3112.

**Closed by wbond** 2016-04-27 17:04 UTC
Labels: C: Java, S: minor, T: bug

**Comment by chuim** [comment] 2016-04-29 21:43
Cool. I'll check it out in the release of the next dev build.
