### ISSUE TITLE
There is no need to include the "text/javscript" type for <script> tags in HTML

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#185] opened 2016-03-29 22:42 UTC
_From @Saket-Komawar on March 25, 2016 18:10_

OS: Linux x86_64(Ubuntu)
Sublime version: Sublime Text Build 3103 on 

When we will try to add  `<script>` tag in HTML file as shown in the first image(initial.png), AutoComplete options will pop up.
Once `<script>` from AutoComplete options is selected, ST will return `<script>` tag as:
`<script type="text/javascript"></script>` 
as shown in second image(final.png).

But there is **NO need** of adding _type="text/javascript"_ attribute as :

> **JavaScript is the default scripting language in HTML.**

![initial](https://cloud.githubusercontent.com/assets/16723595/14049961/9c0c05f8-f2de-11e5-8a88-f60271781880.png)
![final](https://cloud.githubusercontent.com/assets/16723595/14049965/a1908f9e-f2de-11e5-8527-2a55d14927e7.png)

_Copied from original issue: SublimeTextIssues/Core#1157_

**Comment by FichteFoll** [comment] 2016-03-29 22:43
Subtle pointer: https://github.com/sublimehq/Packages/blob/20bb6038d0fb54cc76dc4ef22e810f80fba909e9/HTML/html_completions.py#L296

**Comment by wbond** [comment] 2016-04-23 10:58
This is a duplicate of #156

**Closed by wbond** 2016-04-23 10:58 UTC
Labels: C: HTML, S: trivial, T: enhancement
