### ISSUE TITLE
Perl regular expression highlighting broken

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#8] opened 2014-12-22 12:29 UTC
_From @2shortplanks on October 8, 2014 21:36_

OS and OS version: OS X 10.9.5
Sublime Text Version: Both 2221 and 3065
Did you tried to revert to a freshly installed state? yes
### Bug Description:

Since Perl 5.14 several new regular expression postfix characters have been added, but sublime text doesn't recognize these when highlighting and colors both the characters and the subsequent following text wrong. For example:

![screen shot 2014-10-08 at 5 26 30 pm](https://cloud.githubusercontent.com/assets/46818/4567519/e79e53c4-4f31-11e4-811a-318adc2e6c0e.png)

Note that all text after the `r` is highlighted wrong (for example the `print` is in the quoted color not keyword color)

The current new postfix letters are `r`, `a`, `d`, `l` and `u` (current as of Perl 5.20, latest stable release).  These are documented in the [relevant section of the 5.14 Perl Delta](http://perldoc.perl.org/5.14.0/perldelta.html#Regular-Expressions)
### How to reproduce:

Type this code into the editor and "Set Syntax: Perl"

``` perl
#!/usr/bin/perl

my $foo = "foo";
my $boo = $foo =~ s/f/b/r;
for (1..100) {
  print "$foo $boo\n";
}
```

_Copied from original issue: SublimeTextBugs/Issues#515_

**Comment by pwr22** [comment] 2015-05-19 16:38
This is still an issue and present on Windows 8. Its a major deal breaker in purchasing Sublime for me. I can't have my editor preventing the use of language features

**Comment by 2shortplanks** [comment] 2015-05-19 16:43
Fwiw, using the Modern Perl package, as described above totally solved this for me.

However, this blatantly should be the default. I don't understand how hard it is to incorporate the changes from the package in the core distribution.

**Comment by keith-hall** [comment] 2017-06-14 12:00
https://github.com/sublimehq/Packages/issues/1029

**Comment by gullevek** [comment] 2017-11-24 05:53
Problem still here in 2017

**Comment by gerhardj** [comment] 2017-11-24 05:59
I am using ModernPerl without problems. But I agree this should be merged into core.

**Comment by gullevek** [comment] 2017-11-24 06:01
So do I know, but I expected a bit more from SublimeText

**Comment by FichteFoll** [comment] 2017-11-25 18:11
The default packages are open sourced at sublimehq/Packages and pull requests are welcome. I don't think any of the regular contributors uses Perl, which is why nobody has fixed it so far.

**Comment by FichteFoll** [comment] 2019-11-19 19:24
Cannot reproduce on 3052.

**Closed by FichteFoll** 2019-11-19 19:24 UTC
Labels: C: Perl, S: minor, T: bug
