### ISSUE TITLE
The default syntax highlighting for C ++ parsing error occurs

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#14] opened 2014-12-22 12:31 UTC
_From @forcegroup on September 21, 2014 3:58_

When I use using namespace xxx; several consecutive namespace references become invalid, as shown below
![Sublime](http://static.oschina.net/uploads/space/2014/0921/120611_wsgl_139664.png)

C++11 Parse:
![Sublime](http://static.oschina.net/uploads/space/2014/0921/120752_592D_139664.png)

And if there is such a code
-------------
```C++
#ifdef __cplusplus
extern "C" {
#endif
int foo();
#ifdef __cplusplus
}
#endif
```

:joy: ifdef and endif Unable to match the correct
==========

Syntax highlighting C ++ 11 third-party analytic normal,

SublimeText own syntax highlighting for C ++ parsing error, the impact is all Sublime users, so this problem should be solved owned SublimeText

_Copied from original issue: SublimeTextBugs/Issues#487_

**Comment by jrappen** [comment] 2016-04-26 17:40
Commit has long been merged into sublimehq/packages repo. Cannot reproduce with Build 3111 on Win x64.

**Comment by FichteFoll** [comment] 2016-04-26 22:19
@jrappen thanks for the heads up. I'm slightly out of the loop with this many changes going on and dealing with my own affairs :+1:

**Closed** 2016-04-26 22:18 UTC
Labels: C: C/C++, S: major, T: bug
