### ISSUE TITLE
No auto-indenting in HTML files

### ISSUE THREAD

**Issue by laxman20** [SublimeTextIssues/DefaultPackages#104] opened 2015-02-12 14:51 UTC
HTML documents don't have automatic indentation on the Mac version of Sublime Text.  This works on Windows though.

-Operating system: OSX 10.10 Yosemite
-Sublime Text Version: Version 3, Build 3065
-Steps to reproduce:
    Create an html document.
    Create an opening tag.
    Press Enter.
    Should indent automatically, but in this case, it does not.

**Comment by FichteFoll** [comment] 2015-02-12 16:11
Can someone verify this? There shouldn't really be OS-specific issues here.

**Comment by philipbordallo** [comment] 2015-10-19 06:15
@laxman20 are you talking about when it jumps back on first indent?
![sublime-html](https://cloud.githubusercontent.com/assets/9970403/10570888/f76046b2-75ed-11e5-9387-8a5d651de57a.gif)

**Comment by keith-hall** [comment] 2016-10-25 11:31
https://forum.sublimetext.com/t/auto-indent-from-html-php-on-osx-not-working/22625/4

**Comment by keith-hall** [comment] 2016-10-25 11:34
duplicate of https://github.com/SublimeTextIssues/DefaultPackages/issues/69

**Closed by keith-hall** 2016-10-25 11:34 UTC
